<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\Migrations\AbstractMigration;

final class Version20260921070658 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the Attribute Library aggregate and required system categories and definitions.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql('CREATE TABLE attribute_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, normalized_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_category_normalized_name ON attribute_category (normalized_name)');
        $this->addSql("ALTER TABLE attribute_category ADD CONSTRAINT chk_attribute_category_name_not_blank CHECK (btrim(name) <> '' AND btrim(normalized_name) <> '')");
        $this->addSql('CREATE TABLE attribute_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, normalized_name VARCHAR(255) NOT NULL, description TEXT NOT NULL, type VARCHAR(20) NOT NULL, is_built_in BOOLEAN DEFAULT FALSE NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_definition_normalized_name ON attribute_definition (normalized_name)');
        $this->addSql('CREATE INDEX IDX_6C5628BD12469DE2 ON attribute_definition (category_id)');
        $this->addSql("ALTER TABLE attribute_definition ADD CONSTRAINT chk_attribute_definition_name_not_blank CHECK (btrim(name) <> '' AND btrim(normalized_name) <> '')");
        $this->addSql("ALTER TABLE attribute_definition ADD CONSTRAINT chk_attribute_definition_type CHECK (type IN ('string', 'text', 'image', 'numeric', 'date', 'period', 'boolean', 'select'))");
        $this->addSql('CREATE TABLE attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, sort_order INT NOT NULL, attribute_definition_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_option_position ON attribute_option (attribute_definition_id, sort_order)');
        $this->addSql('CREATE UNIQUE INDEX uniq_attribute_option_label ON attribute_option (attribute_definition_id, label)');
        $this->addSql('CREATE INDEX IDX_78672EEA7492F274 ON attribute_option (attribute_definition_id)');
        $this->addSql('ALTER TABLE attribute_option ADD CONSTRAINT chk_attribute_option_sort_order CHECK (sort_order >= 0)');
        $this->addSql("ALTER TABLE attribute_option ADD CONSTRAINT chk_attribute_option_label_not_blank CHECK (btrim(label) <> '')");
        $this->addSql('ALTER TABLE attribute_definition ADD CONSTRAINT FK_6C5628BD12469DE2 FOREIGN KEY (category_id) REFERENCES attribute_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attribute_option ADD CONSTRAINT FK_78672EEA7492F274 FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("INSERT INTO attribute_category (name, normalized_name) VALUES ('Certification', 'certification'), ('Domain Knowledge', 'domain knowledge'), ('Personal Information', 'personal information'), ('Soft Skills', 'soft skills')");
        $this->addSql("INSERT INTO attribute_definition (category_id, name, normalized_name, description, type, is_built_in, version, created_at, updated_at)
            SELECT category.id, seed.name, seed.normalized_name, '', seed.type, TRUE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            FROM attribute_category category
            CROSS JOIN (VALUES
                ('First Name', 'first name', 'string'),
                ('Last Name', 'last name', 'string'),
                ('Location', 'location', 'string'),
                ('Personal Photo', 'personal photo', 'image')
            ) AS seed(name, normalized_name, type)
            WHERE category.normalized_name = 'personal information'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE attribute_option');
        $this->addSql('DROP TABLE attribute_definition');
        $this->addSql('DROP TABLE attribute_category');
    }
}
