<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260923100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add dynamic CV identity and publication state.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql('CREATE TABLE cv (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, profile_id INT NOT NULL, position_id INT NOT NULL, status VARCHAR(12) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_profile_position ON cv (profile_id, position_id)');
        $this->addSql('CREATE INDEX idx_cv_position_status ON cv (position_id, status)');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_CV_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_CV_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql("ALTER TABLE cv ADD CONSTRAINT chk_cv_status CHECK (status IN ('DRAFT', 'PUBLISHED'))");
        $this->addSql("ALTER TABLE cv ADD CONSTRAINT chk_cv_published_at CHECK ((status = 'DRAFT' AND published_at IS NULL) OR (status = 'PUBLISHED' AND published_at IS NOT NULL))");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cv');
    }
}
