<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260921223500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add social authentication roles, blocking, and provider identities.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql("ALTER TABLE app_user ADD roles JSON DEFAULT '[]' NOT NULL");
        $this->addSql('ALTER TABLE app_user ADD blocked BOOLEAN DEFAULT FALSE NOT NULL');
        $this->addSql('CREATE TABLE oauth_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, provider VARCHAR(20) NOT NULL, provider_user_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6E30F9D1A76ED395 ON oauth_account (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_oauth_provider_identity ON oauth_account (provider, provider_user_id)');
        $this->addSql('ALTER TABLE oauth_account ADD CONSTRAINT FK_OAUTH_ACCOUNT_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql("ALTER TABLE oauth_account ADD CONSTRAINT chk_oauth_provider CHECK (provider IN ('google', 'github'))");
        $this->addSql("ALTER TABLE oauth_account ADD CONSTRAINT chk_oauth_provider_user_id CHECK (btrim(provider_user_id) <> '')");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE oauth_account');
        $this->addSql('ALTER TABLE app_user DROP roles');
        $this->addSql('ALTER TABLE app_user DROP blocked');
    }
}
