<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260923110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add immutable Position discussion posts and unique CV likes.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');
        $this->addSql('CREATE TABLE discussion_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position_id INT NOT NULL, author_user_id INT NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_discussion_post_position_order ON discussion_post (position_id, created_at, id)');
        $this->addSql('CREATE INDEX idx_discussion_post_position_incremental ON discussion_post (position_id, id)');
        $this->addSql('ALTER TABLE discussion_post ADD CONSTRAINT FK_DISCUSSION_POST_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion_post ADD CONSTRAINT FK_DISCUSSION_POST_AUTHOR FOREIGN KEY (author_user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE TABLE cv_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cv_id INT NOT NULL, recruiter_user_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_like_cv_recruiter ON cv_like (cv_id, recruiter_user_id)');
        $this->addSql('CREATE INDEX idx_cv_like_recruiter ON cv_like (recruiter_user_id)');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CV_LIKE_CV FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CV_LIKE_RECRUITER FOREIGN KEY (recruiter_user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cv_like');
        $this->addSql('DROP TABLE discussion_post');
    }
}
