<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260922162142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Candidate Projects and reusable technology Tags.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql('CREATE TABLE candidate_project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_candidate_project_recent ON candidate_project (profile_id, end_date, start_date, id)');
        $this->addSql('CREATE INDEX IDX_A0627D4FCCFA12B8 ON candidate_project (profile_id)');
        $this->addSql('CREATE TABLE candidate_project_tag (project_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (project_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_50A1B7DC166D1F9C ON candidate_project_tag (project_id)');
        $this->addSql('CREATE INDEX IDX_50A1B7DCBAD26311 ON candidate_project_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, normalized_name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tag_normalized_name ON tag (normalized_name)');
        $this->addSql('ALTER TABLE candidate_project ADD CONSTRAINT FK_A0627D4FCCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_project_tag ADD CONSTRAINT FK_50A1B7DC166D1F9C FOREIGN KEY (project_id) REFERENCES candidate_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_project_tag ADD CONSTRAINT FK_50A1B7DCBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql("ALTER TABLE candidate_project ADD CONSTRAINT chk_candidate_project_name CHECK (btrim(name) <> '')");
        $this->addSql('ALTER TABLE candidate_project ADD CONSTRAINT chk_candidate_project_period CHECK (end_date IS NULL OR start_date <= end_date)');
        $this->addSql("ALTER TABLE tag ADD CONSTRAINT chk_tag_names CHECK (btrim(name) <> '' AND btrim(normalized_name) <> '')");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE candidate_project_tag');
        $this->addSql('DROP TABLE candidate_project');
        $this->addSql('DROP TABLE tag');
    }
}
