<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260923010100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add shared Positions, templates, project tags, typed access rules, and optimistic locking.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, short_description TEXT NOT NULL, access_type VARCHAR(20) NOT NULL, max_projects INT NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_position_listing ON position (updated_at, id)');
        $this->addSql('CREATE INDEX idx_position_access ON position (access_type, updated_at, id)');
        $this->addSql("ALTER TABLE position ADD CONSTRAINT chk_position_title CHECK (btrim(title) <> '')");
        $this->addSql('ALTER TABLE position ADD CONSTRAINT chk_position_description_length CHECK (char_length(short_description) <= 2000)');
        $this->addSql("ALTER TABLE position ADD CONSTRAINT chk_position_access_type CHECK (access_type IN ('public', 'restricted'))");
        $this->addSql('ALTER TABLE position ADD CONSTRAINT chk_position_max_projects CHECK (max_projects >= 0)');

        $this->addSql('CREATE TABLE position_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position_id INT NOT NULL, attribute_definition_id INT NOT NULL, sort_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_attribute_definition ON position_attribute (position_id, attribute_definition_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_ATTRIBUTE_POSITION ON position_attribute (position_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_ATTRIBUTE_DEFINITION ON position_attribute (attribute_definition_id)');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_POSITION_ATTRIBUTE_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_POSITION_ATTRIBUTE_DEFINITION FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT chk_position_attribute_sort_order CHECK (sort_order >= 0)');

        $this->addSql('CREATE TABLE position_project_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_position_project_tag ON position_project_tag (position_id, tag_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_PROJECT_TAG_POSITION ON position_project_tag (position_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_PROJECT_TAG_TAG ON position_project_tag (tag_id)');
        $this->addSql('ALTER TABLE position_project_tag ADD CONSTRAINT FK_POSITION_PROJECT_TAG_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_project_tag ADD CONSTRAINT FK_POSITION_PROJECT_TAG_TAG FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE position_access_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position_id INT NOT NULL, attribute_definition_id INT NOT NULL, option_id INT DEFAULT NULL, operator VARCHAR(30) NOT NULL, text_value TEXT DEFAULT NULL, numeric_value NUMERIC(20, 6) DEFAULT NULL, date_value DATE DEFAULT NULL, period_start DATE DEFAULT NULL, period_end DATE DEFAULT NULL, boolean_value BOOLEAN DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_POSITION_ACCESS_RULE_POSITION ON position_access_rule (position_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_ACCESS_RULE_DEFINITION ON position_access_rule (attribute_definition_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_ACCESS_RULE_OPTION ON position_access_rule (option_id)');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_POSITION_ACCESS_RULE_POSITION FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_POSITION_ACCESS_RULE_DEFINITION FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_POSITION_ACCESS_RULE_OPTION FOREIGN KEY (option_id) REFERENCES attribute_option (id) NOT DEFERRABLE');
        $this->addSql("ALTER TABLE position_access_rule ADD CONSTRAINT chk_position_rule_operator CHECK (operator IN ('equal', 'not_equal', 'greater_than', 'greater_than_or_equal', 'less_than', 'less_than_or_equal'))");
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT chk_position_rule_period_complete CHECK ((period_start IS NULL) = (period_end IS NULL))');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT chk_position_rule_period_order CHECK (period_start IS NULL OR period_start <= period_end)');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT chk_position_rule_single_kind CHECK (num_nonnulls(text_value, numeric_value, date_value, period_start, boolean_value, option_id) = 1)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE position_access_rule');
        $this->addSql('DROP TABLE position_project_tag');
        $this->addSql('DROP TABLE position_attribute');
        $this->addSql('DROP TABLE position');
    }
}
