<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260921220047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Candidate Profile ownership and single typed attribute value storage.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'This migration requires PostgreSQL.');

        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, normalized_email VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_app_user_normalized_email ON app_user (normalized_email)');
        $this->addSql("ALTER TABLE app_user ADD CONSTRAINT chk_app_user_email_not_blank CHECK (btrim(email) <> '' AND btrim(normalized_email) <> '')");

        $this->addSql('CREATE TABLE profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_profile_user ON profile (user_id)');
        $this->addSql('ALTER TABLE profile ADD CONSTRAINT FK_8157AA0FA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE profile_attribute_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text_value TEXT DEFAULT NULL, numeric_value NUMERIC(20, 6) DEFAULT NULL, date_value DATE DEFAULT NULL, period_start DATE DEFAULT NULL, period_end DATE DEFAULT NULL, boolean_value BOOLEAN DEFAULT NULL, image_key VARCHAR(255) DEFAULT NULL, profile_id INT NOT NULL, attribute_definition_id INT NOT NULL, option_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_profile_attribute_definition ON profile_attribute_value (profile_id, attribute_definition_id)');
        $this->addSql('CREATE INDEX IDX_930915A8CCFA12B8 ON profile_attribute_value (profile_id)');
        $this->addSql('CREATE INDEX IDX_930915A87492F274 ON profile_attribute_value (attribute_definition_id)');
        $this->addSql('CREATE INDEX IDX_930915A8A7C41D6F ON profile_attribute_value (option_id)');
        $this->addSql('ALTER TABLE profile_attribute_value ADD CONSTRAINT FK_930915A8CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_attribute_value ADD CONSTRAINT FK_930915A87492F274 FOREIGN KEY (attribute_definition_id) REFERENCES attribute_definition (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_attribute_value ADD CONSTRAINT FK_930915A8A7C41D6F FOREIGN KEY (option_id) REFERENCES attribute_option (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_attribute_value ADD CONSTRAINT chk_profile_value_period_complete CHECK ((period_start IS NULL) = (period_end IS NULL))');
        $this->addSql('ALTER TABLE profile_attribute_value ADD CONSTRAINT chk_profile_value_period_order CHECK (period_start IS NULL OR period_start <= period_end)');
        $this->addSql('ALTER TABLE profile_attribute_value ADD CONSTRAINT chk_profile_value_single_kind CHECK (num_nonnulls(text_value, numeric_value, date_value, period_start, boolean_value, option_id, image_key) <= 1)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE profile_attribute_value');
        $this->addSql('DROP TABLE profile');
        $this->addSql('DROP TABLE app_user');
    }
}
